{
  sentinel,
  hyprland,
  gaming-edge,
  cachyos,
  quickshell,
  hyprpwcenter,
  ...
}:
[
  sentinel.overlays.default
  hyprland.overlays.default
  cachyos.overlays.pinned
  gaming-edge.overlays.default
  quickshell.overlays.default
  hyprpwcenter.overlays.default
]
