require("hyprland.variables") -- Auto generated by nix
require("hyprland.rules.monitors") -- Must be loaded first to parse monitors

require("hyprland.rules")
require("hyprland.settings")
require("hyprland.keybinds")
require("hyprland.patches")

hl.notification.create({ text = "Hyprland reloaded", duration = "2000", icon = "ok" })
