require("hyprland.variables") -- Auto generated by nix

require("hyprland.monitors") -- Must be loaded first to parse monitors

require("hyprland.rules")
require("hyprland.settings")
require("hyprland.keybinds")
require("hyprland.patches")
