name: Nix Flake Check
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Nix Targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Build default package
        run: nix build
